client/src/App.tsx, client/src/component/Board/Board.tsx, client/src/component/Posts/Posts.tsx
> 게시글이 Board 였는데 회의결과 Post로 변경되서 관련 코드, 이름들을 수정했습니다.
=> rename : Board -> Posts

server/db/sql/refresh_tokens.sql
=> feat: refresh_token 테이블 추가

server/app.js, server/utils/errors.js
- 서버에서 발생할 수 있는 에러를 통합한 ServerError 클래스를 정의했습니다.
- 이후, 이를 통한 error 핸들링 미들웨어를 구현했습니다.
```js
const ServerError = require('errors.js 경로');
const addUser = (req, res, next) => {
try {
if(!req.body.email){
throw ServerError.badRequest("이메일을 제대로 입력해주세요");
}
// 이후 회원가입 로직...
} catch (err) {
next(err);
}
}
```
- 미들웨어의 이상한 점? 고쳤으면 하는 부분? (단순 이름 변경도 OK)
- 다른 좋은 방식으로 구현할 수 있다면 소개 부탁!
=> feat : error handling middleware 추가

server/app.ts
=> fix: error 핸들러 작동안하는 문제 수정

server/route/users_router.ts, server/utils/validations/users/constants.ts, server/utils/validations/users/user.ts
- #54
- /utils/validations/users 에 user.ts / constants.ts 로 작성했는데 폴더이름/위치, 파일 이름 괜찮나요?
=> [BE] user_router 유효성 검사 리팩토링

server/db/context/posts_context.ts
깜빡하고 게시글 삭제 기능을 만들 때 sql로 delete문을 사용해서
isDelete 를 ture로 update하도록 수정했습니다.
LGTM 2개 생기면 바로 merge 하겠습니다.
=> refactor : delete -> update isDelete = true

server/controller/posts_controller.ts, server/route/posts_router.ts
comment, user controller 따라서 함수 이름들을 handle ~ CRUD 로 바꿨습니다!
=> refactor : post controller 함수 이름 변경

server/route/posts_router.ts, server/utils/validations/posts/constants.ts, server/utils/validations/posts/posts.ts
posts router에 있던 validation을 user 처럼 싹 정리했습니다.
=> refactor : posts validation 정리

client/package.json, client/src/App.css.ts, client/vite.config.ts
회의 때 정했던 client 개발에 필요한 css package를 추가하고 설정했습니다.
Zustand는 안넣었으니까 나중에 하실 때 말씀해주세요!
=> [FE] client package 추가

server/controller/users_controller.ts, server/db/context/users_context.ts
- #70
- result 내용에 추가/제거 할 항목 있을까요? (이 항목이 zustand에서 각각 state로 들어갈거 같습니다.)
- 지금 현재 보내는 시간이 UTC 시간인데 한국시간으로 바꿀까요?
- 시간 포맷이 ISO 방식인데 다른 포맷으로 보낼까요?
=> [BE] 로그인 API response 내용 추가

client/package.json, client/src/component/TestMain/Tests.tsx, client/src/page/User/Login.tsx, client/src/state/selector.ts, client/src/state/store.ts, server/controller/users_controller.ts
- #78
잘못 구현된 부분이나 이상한 부분 있으면 말해주세요.
=> [FE] zustand 세팅

client/src/App.tsx, client/src/component/User/EmailForm.css.ts, client/src/component/User/EmailForm.tsx, client/src/component/User/ErrorMessageForm.tsx, client/src/component/User/InputField.css.ts, client/src/component/User/InputField.tsx, client/src/component/User/PasswordForm.tsx, client/src/component/User/SubmitButton.css.ts, client/src/component/User/SubmitButton.tsx, client/src/page/User/Join.tsx, client/src/page/User/Login.css.ts, client/src/page/User/Login.tsx, client/src/page/User/User.tsx
- 회원가입 화면 개발하기전에 회원가입 화면에서 사용될 폼들을 미리 리팩토링 했습니다.
=> [FE] 로그인 화면 리펙토링

client/src/page/User/Login.tsx, client/src/state/store.ts
- #85
- 로그인 화면 접속시 로컬 스토리지를 초기화 하지 않으면 오류가 생기는 버그가 있습니다. 임시 방편으로 해결을 했으나 정확한 원인이 파악이 안됩니다. 원인 혹은 해결 방법 찾으면 이슈 남겨주세요.(수정 완료)
=> [FE] state 값을 로컬 스토리지에 저장

client/src/api/likes/crud.ts, client/src/api/posts/crud.ts, client/src/component/Posts/Modal/DeleteModal.css.ts, client/src/component/Posts/Modal/DeleteModal.tsx, client/src/component/Posts/Modal/PostModal.css.ts, client/src/component/Posts/Modal/PostModal.tsx, client/src/component/Posts/PostInfo.css.ts, client/src/component/Posts/PostInfo.tsx
- PostInfo의 버튼들에 기능, 스타일 적용
- userLiked 가 true -> 클릭 시, 좋아요 삭제 요청 + state 변경 (userLiked->false, likes ->likes-1)
- userLiked 가 false -> 클릭 시, 좋아요 생성 요청 + state 변경 (userLiked->true, likes ->likes+1)
- 생성/수정 모달 일부 수정
- 시연 영상
https://github.com/user-attachments/assets/a895d405-f208-4903-af27-e37628f77e22
- z-index 설정 이유
- 이상한 부분 있으면 알려주세요!!
=> [FE] 게시글 내용 보기 페이지2

client/src/App.tsx, client/src/api/users/crud.ts, client/src/component/Header/DropdownMenu.css.ts, client/src/component/Header/DropdownMenu.tsx, client/src/component/Header/Header.tsx, client/src/page/User/CheckPassword.css.ts, client/src/page/User/CheckPassword.tsx, client/src/page/User/User.tsx
=> [FE] 회원 정보 클릭시 드랍다운메뉴 추가

client/src/api/users/crud.ts, client/src/component/Header/DropdownMenu.tsx, client/src/component/Header/Header.tsx, client/src/component/Header/UserDeleteModal.css.ts, client/src/component/Header/UserDeleteModal.tsx, client/src/hook/useModal.ts, client/src/page/User/CheckPassword.tsx, client/src/page/User/User.tsx
- #98
- 원래 예정했던 기능들은 다 구현한거 같아서 아마 앞으로는 리팩토링 하고 코드에 남겨놓은 TODO들 해결할꺼 같습니다.
TODO남겨 놓은 것들이 좀 작은규모라 아마 TODO 여러개를 한번에 PR올리게 될거 같습니다.
- 유저쪽 더 필요한거 같은 기능 있으면 말해주세요.
=> [FE] 회원탈퇴 확인 모달 추가

client/src/api/api.ts, client/src/component/Header/Header.tsx, client/src/page/User/CheckPassword.tsx, server/middleware/auth.ts
- #109 
클라이언트의 클라이언트의 로그인 상태를 강제 로그아웃으로 변경
- 또 다른 오류가 생길 경우 말해주세요.
=> [FE]client login 상태 관리

client/src/component/Chats/ChatRoom/ChatRoom.tsx
- IMessage interface를 추가
- 테스트 채팅 기록(IMessage[]) 데이터 추가
- 메세지 렌더링 기능 추가
- IMessage.is_system 으로 시스템 메세지 구분해서 렌더링
- IMessage.is_mine으로 나의 메세지, 상대방 메세지 구분해서 렌더링
- 로직만 추가한 것이고 출력되는 결과는 같아서 refactor로 함
- 특별히 바뀐게 없기 떄문에 코드 확인만 하면 머지할 예정
- 혹시 코드가 이상한 부분이 있다면 알려주세요~!
=> 채팅방 (채팅 aside) 메세지 렌더링 기능

client/src/api/chats/crud.ts, client/src/component/Chats/ChatRooms/ChatRooms.tsx, client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx, client/src/utils/detectMode.ts, server/controller/chats_controller.ts, server/db/context/chats_context.ts, server/route/chats_router.ts, shared/chats/mappers.ts
#152 
-   [x] 성공 시, IReadRoomResponse 반환
- 중복되는 코드는 추후에 수정할 예정입니다.
=> [채팅] 채팅방 조회 기능

client/src/component/Chats/ChatRooms/ChatRooms.tsx, client/src/component/Chats/ChatRooms/MyChatRooms.tsx, client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx, client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
- 채팅방 검색 기능
- 내 채팅방 검색 기능
- 기능 구현하려고 FE 파일 좀 바꿨습니다. 이해 필요한 부분 있으시면 글 남겨주세요
- 따로 추가 사항 없으면 마지막에 보신 분이 머지 해주세요!!
=>  내 채팅방 리스트 조회, 채팅방 검색 기능 완성

client/src/component/Chats/ChatRooms/test-case.ts
- roomId 가 string -> number 로 바뀌면서 기존 test data에서 타입에러가 발생해 이를 수정함
=> 🐛 [fix] : dto 변경에 따른 테스트 케이스 타입 에러 수정

client/src/App.tsx, client/src/component/Admin/AdminSidebar.css.ts, client/src/component/Admin/AdminSidebar.tsx, client/src/component/Admin/UserMgmt/EmptyUserList.tsx, client/src/component/Admin/UserMgmt/UserList.css.ts, client/src/component/Admin/UserMgmt/UserList.tsx, client/src/component/Header/DropdownMenu.tsx, client/src/page/Admin/AdminPostMgmtPage.tsx, client/src/page/Admin/AdminStatsPage.tsx, client/src/page/Admin/AdminUserMgmtPage.css.ts, client/src/page/Admin/AdminUserMgmtPage.tsx, shared/admin/users.ts, shared/index.ts
> #146 
-   [x] 관리자 페이지 이동 사이드바 구현
-   [x] 사용자 검색 기능 구현
-   [x] 유저 데이터 (닉네임, 이메일, 가입일, 댓글 수 , 게시글 수, 사용자 로그, 계정 삭제/복구) 출력
-   [x] isDelete 필드에 따른 삭제/복구 기능 구현
> 오류가 나거나 다른 좋은 의견 있으신 분들은 언제나 환영입니다 ~👍 
> 디자인은 기능 구현 다 끝나고 나서 바꿔볼게요👯
=> [FE] 사용자 관리 게시판 구현

client/src/component/Admin/PostMgmt/EmptyPostList.tsx, client/src/component/Admin/PostMgmt/PostMgmt.css.ts, client/src/component/Admin/PostMgmt/PostMgmt.tsx, client/src/component/Admin/PostMgmt/PostMgmtAction.ts, client/src/component/Admin/PostMgmt/PostMgmtItem.tsx, client/src/component/Admin/UserMgmt/UserList.tsx, client/src/page/Admin/AdminPostMgmtPage.tsx, client/src/page/Admin/AdminUserMgmtPage.tsx, shared/admin/posts.ts, shared/index.ts
> #156 
-   [x] 게시물 검색 기능
-   [x] 게시물 -제목, 작성자, 작성일, 상태(공개/비공개), 삭제 정보 UI 구현
-   [x] 제목 선택 시 게시글로 이동 
-   [x] 게시글 상태 변경  기능(공개/비공개) 
(비공개 데이터는 통계에 추가 / 후에 시간 남으면 비밀글 기능 생각중)
-   [x] 게시글 삭제/ 복구 기능
> 오류가 나거나 다른 좋은 의견 있으신 분들은 언제나 환영입니다 ~👍 
> 디자인은 기능 구현 다 끝나고 나서 바꿔볼게요👯
=> [FE] 게시글 관리 게시판 구현

chat_server/app.ts, client/package.json, client/src/App.tsx, client/src/component/Header/Header.tsx, client/src/page/User/Login.tsx
> #149 
> - `App.tsx`에서 socket 상태 관리를 하고, socket event 필요한 컴포넌트에 props 전달  
> - 로그인 성공 시, 소켓 연결(connect)
> - 로그아웃 시, 소켓 연결 끊김(disconnect)
- 먼저 확인하신분 있으면 Merge 부탁드립니다!
=> 로그인/로그아웃, 소켓 연결

server/controller/chats_controller.ts, server/db/context/chats_context.ts, server/route/chats_router.ts, shared/chats/chat-room.ts
- 채팅방을 탈퇴하는 api
-  request : roomId
-  기능 : members table에서 userId, roomId가 일치하는 row의 is_deleted = true로 변경
-  response : status 200으로 구분 (따로 response type이 필요 없음)
=> [채팅] 채팅방 탈퇴 api 구현

chat_server/events/chatroom_events.ts, chat_server/utils/api.ts, client/src/App.tsx, client/src/component/Chats/ChatRoom/ChatRoom.tsx, client/src/component/Chats/ChatRooms/ChatRooms.tsx, client/src/component/Chats/ChatRooms/MyChatRooms.tsx, client/src/component/Chats/ChatRooms/Rooms/Room.tsx, shared/chats/chat-room.ts, shared/chats/dto.ts
- flow diagram에서 다음 내용을 제외한 작업을 완료했습니다.
- 현재 `/api/chat/join` api 요청시, `500 Error` 가 발생합니다. 
- 호준님, `메세지 캐싱` 코드 작업 완료시, 참고해서 추가할 예정입니다.
<br>
<br>
<br>
> 1. `POST : /chat/api/join` 500 error가 발생합니다.
> 2. 비밀 채팅방 가입시, 해당 API에 password 일치 조건 로직이 없는것같은데, 이는 어떻게 구현해야할까요?
> 3. kafka 메세지 DB 저장을 위해 sendMessage()를 했지만, DB에 저장되지가 않습니다.(89aa00de702c0a206e1f4a52df3714e85e26a57d)
=> [FE/BE] 채팅방 가입 기능

server/controller/oauth_controller.ts, server/controller/users_controller.ts, server/db/context/oauth_context.ts, server/db/context/users_context.ts, server/route/oauth_router.ts, server/route/users_router.ts, server/utils/oauth/oauth.ts, server/utils/validations/oauth/oauth.ts, server/utils/validations/users/user.ts
- #159
&nbsp;
- 이미 어느 유저에게 연동한 소셜 계정 → 오류
- 소셜 연동 사실 없음 → 오류
- 이메일 등록 없음 AND 소셜 연동 하나 남음 → 오류 (회원탈퇴 기능을 사용해야 하는 상황)
- 그 외 → 소셜 연동 해제 처리
- 이메일 정보가 없는 유저에 한하여, 비밀번호와 함께 최초 1회 이메일 등록 가능 (회원 정보 수정 페이지에 접근하기 위한 비밀번호 확인 절차는 소셜 로그인 재확인으로 대체 가능)
&nbsp;
- 메서드: `GET`
- 엔드포인트: `/api/oauth/link-url/{provider}`
- Params
- provider: `google | kakao | naver`
- 특이사항
- #192 에서와 같이, 어떤 기능으로(로그인, 탈퇴, 연동 추가) 연결되는지 구분하기 위해 <mark>state 서치 파라미터를 `login_type=link`로 세팅하며, Redirect URI까지 이 파라미터가 전달됩니다.</mark>
- 메서드: `POST`
- 엔드포인트: `/api/oauth/link`
- 로그인 필요
- Request body
```typescript
{
"provider": "google" | "kakao" | "naver",
"code": string
}
```
- 메서드: `DELETE`
- 엔드포인트: `/api/oauth/link/{provider}`
- Params
- provider: `google | kakao | naver`
- 로그인 필요
- Request body 없음
- 메서드: `GET`
- 엔드포인트: `/api/user`
- 로그인 …
=> [BE] 소셜 로그인 회원 정보 수정, 연동 추가·해제 API 구현

client/src/component/Header/Header.tsx, client/src/state/ChatRoomStore.ts
#206
- 채팅 관련 state를 초기화하는 initializeState 추가
- 로그 아웃 시, initializeState 동작
- 로그 아웃 끝나면 메인 페이지로 이동
- 간단한 거라서 먼저 발견하신 분이 머지해주세요~
=> 🐛 [fix] : 로그 아웃 -> 채팅 관련 state 초기화 + 메인 페이지로 이동

server/controller/posts_controller.ts, server/db/context/posts_context.ts
- #181
-   [x] 비공개 게시글 게시글 목록에 안보이는 기능 추가
-   [x] 비공개 게시글은 글 쓴 본인만 보이게 수정
=> [BE] 게시글 비공개기능 구현

nestjs-migration/src/user/constant/user.constants.ts, nestjs-migration/src/user/dto/check-password.dto.ts, nestjs-migration/src/user/user.controller.spec.ts, nestjs-migration/src/user/user.controller.ts, nestjs-migration/src/user/user.service.spec.ts, nestjs-migration/src/user/user.service.ts
- #220
- 로그아웃 API 마이그레이션
- 비밀번호 재확인 API 마이그레이션
=> [BE] 로그아웃, 비밀번호 재확인 API 마이그레이션

nestjs-migration/package.json, nestjs-migration/src/app.module.ts, nestjs-migration/src/main.ts, nestjs-migration/src/oauth/constants/oauth-token-service.constatns.ts, nestjs-migration/src/oauth/dto/oauth-login.dto.ts, nestjs-migration/src/oauth/entities/oauth-connection.entity.ts, nestjs-migration/src/oauth/entities/oauth-provider.entity.ts, nestjs-migration/src/oauth/oauth.controller.spec.ts, nestjs-migration/src/oauth/oauth.controller.ts, nestjs-migration/src/oauth/oauth.module.ts, nestjs-migration/src/oauth/oauth.service.spec.ts, nestjs-migration/src/oauth/oauth.service.ts, nestjs-migration/src/oauth/oauthtoken.service.spec.ts, nestjs-migration/src/oauth/oauthtoken.service.ts, nestjs-migration/src/oauth/repositories/oauth-connection.repository.ts, nestjs-migration/src/oauth/repositories/oauth-provider.repository.ts, nestjs-migration/src/user/user.repository.ts, nestjs-migration/src/utils/oauth.util.ts
- #238
- 소셜 로그인 처리 API 마이그레이션
- 로그인시 트랜젝션 적용
- 서비스쪽 테스트코드에 중복코드가 많아서 추후에 리팩토링 하도록 하겠습니다.
=> [BE] 소셜 로그인 처리 API 마이그레이션

nestjs-migration/src/oauth/oauth.controller.spec.ts, nestjs-migration/src/oauth/oauth.controller.ts, nestjs-migration/src/oauth/oauth.service.spec.ts, nestjs-migration/src/oauth/oauth.service.ts
- #238
- 소셜 로그인 재확인 URL 조회 API 마이그레이션
- 소셜 로그인 재확인 처리 마이그레이션
=> [BE] 소셜 로그인 재확인 마이그레이션

nestjs-migration/src/oauth/oauth.controller.spec.ts, nestjs-migration/src/oauth/oauth.controller.ts, nestjs-migration/src/oauth/oauth.service.spec.ts, nestjs-migration/src/oauth/oauth.service.ts, nestjs-migration/src/oauth/oauthtoken.service.spec.ts, nestjs-migration/src/oauth/oauthtoken.service.ts, nestjs-migration/src/oauth/repositories/oauth-connection.repository.ts, nestjs-migration/src/utils/oauth.util.ts
- #238
- 연동 추가를 위한 소셜 로그인 URL 조회 API 마이그레이션
- 소셜 로그인 연동 추가 처리 API 마이그레이션
- 소셜 로그인 연동 해제 API 마이그레이션
=> [BE] 소셜 로그인 연동 추가 및 해제 마이그레이션

nestjs-migration/src/admin/admin.controller.spec.ts, nestjs-migration/src/admin/admin.controller.ts, nestjs-migration/src/admin/admin.module.ts, nestjs-migration/src/admin/admin.service.spec.ts, nestjs-migration/src/admin/admin.service.ts, nestjs-migration/src/admin/dto/get-stats.dto.ts, nestjs-migration/src/comment/comment.module.ts, nestjs-migration/src/comment/comment.repository.ts, nestjs-migration/src/common/guard/token.guard.ts, nestjs-migration/src/log/constants/log.constants.ts, nestjs-migration/src/log/dto/get-log-query.dto.ts, nestjs-migration/src/log/dto/get-log.dto.ts, nestjs-migration/src/log/entities/log-category.entity.ts, nestjs-migration/src/log/entities/log.entity.ts, nestjs-migration/src/log/log.module.ts, nestjs-migration/src/log/log.repository.ts, nestjs-migration/src/log/log.service.spec.ts, nestjs-migration/src/log/log.service.ts, nestjs-migration/src/post/post.repository.ts, nestjs-migration/src/user/user.repository.ts
=> [BE] 통계 API 마이그레이션

nestjs-migration/src/admin/admin.controller.spec.ts, nestjs-migration/src/admin/admin.controller.ts, nestjs-migration/src/admin/admin.module.ts, nestjs-migration/src/admin/admin.service.spec.ts, nestjs-migration/src/admin/admin.service.ts, nestjs-migration/src/admin/dto/get-posts.dto.ts, nestjs-migration/src/admin/dto/get-stats.dto.ts, nestjs-migration/src/admin/dto/get-users.dto.ts, nestjs-migration/src/comment/comment.module.ts, nestjs-migration/src/comment/comment.repository.ts, nestjs-migration/src/common/guard/token.guard.ts, nestjs-migration/src/log/constants/log.constants.ts, nestjs-migration/src/log/dto/get-log-query.dto.ts, nestjs-migration/src/log/dto/get-log.dto.ts, nestjs-migration/src/log/entities/log-category.entity.ts, nestjs-migration/src/log/entities/log.entity.ts, nestjs-migration/src/log/log.module.ts, nestjs-migration/src/log/log.repository.ts, nestjs-migration/src/log/log.service.spec.ts, nestjs-migration/src/log/log.service.ts, nestjs-migration/src/post/post.repository.ts, nestjs-migration/src/user/user.repository.ts
=> [BE] 게시글 관리 API 마이그레이션

nestjs-migration/src/admin/admin.controller.spec.ts, nestjs-migration/src/admin/admin.controller.ts, nestjs-migration/src/admin/admin.module.ts, nestjs-migration/src/admin/admin.service.spec.ts, nestjs-migration/src/admin/admin.service.ts, nestjs-migration/src/admin/dto/get-posts.dto.ts, nestjs-migration/src/admin/dto/get-stats.dto.ts, nestjs-migration/src/admin/dto/get-users.dto.ts, nestjs-migration/src/app.module.ts, nestjs-migration/src/comment/comment.module.ts, nestjs-migration/src/comment/comment.repository.ts, nestjs-migration/src/common/guard/rbac.guard.ts, nestjs-migration/src/common/guard/token.guard.ts, nestjs-migration/src/log/constants/log.constants.ts, nestjs-migration/src/log/dto/get-log-query.dto.ts, nestjs-migration/src/log/dto/get-log.dto.ts, nestjs-migration/src/log/entities/log-category.entity.ts, nestjs-migration/src/log/entities/log.entity.ts, nestjs-migration/src/log/log.module.ts, nestjs-migration/src/log/log.repository.ts, nestjs-migration/src/log/log.service.spec.ts, nestjs-migration/src/log/log.service.ts, nestjs-migration/src/post/post.repository.ts, nestjs-migration/src/user/user.repository.ts, nestjs-migration/src/user/user.service.ts
=> [BE] 사용자 관리 API 마이그레이션

client/src/component/Comments/CommentForm/CommentForm.tsx, client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx, client/src/component/Comments/Comments.tsx, client/src/component/Header/DropdownMenu.tsx, client/src/component/Header/Header.tsx, client/src/component/Posts/Modal/DeleteModal.css.ts, client/src/component/Posts/Modal/PostModal.css.ts, client/src/component/Posts/PostInfo.tsx, client/src/component/Posts/PostList/MainPostList.tsx, client/src/component/Posts/PostList/PostList.tsx, client/src/component/Posts/Rank/UserRank.tsx, client/src/component/User/DuplicationCheckButton.tsx, client/src/component/User/InputField.tsx, client/src/component/common/Button.tsx, client/src/component/common/Pagination/Pagination.tsx, client/src/component/common/SearchForm/SearchForm.tsx, client/src/component/common/Textarea.tsx, client/src/index.css, client/src/page/Category/Community.tsx, client/src/page/Main/Main.tsx, client/src/page/User/Join.tsx, client/src/page/User/Login.tsx, client/src/state/ThemeStore.ts, client/tailwind.config.js
>  #274 
> 토글 버튼을 이용한 다크모드/라이트모드 추가
> 저번 PR에 추가했던 부분들은 전부 다크모드/라이트모드 수정 완료
샷 (선택)
> 오류나 더 좋은 의견이 있다면 말씀해주세요!😃
=> [FE] 다크모드/라이트모드 추가

nestjs-migration/src/app.module.ts
nest AppModule에서 AdminModule이 삭제 되어있어서 재등록 했습니다.
- 수정사항 알리기위해서 reviewer에 등록 했습니다. 바로 머지 하도록 하겠습니다.
=> [fix] App모듈에 삭제되었던 Admin 모듈 다시 등록

client/src/App.tsx, client/src/component/Admin/Stats/AdminGraph.tsx, client/src/component/Admin/Stats/ChartData.ts, client/src/component/Posts/PostList/MainPostList.tsx, client/src/component/Posts/Rank/UserRank.tsx, client/src/component/common/Confetti/Confetti.tsx, client/src/page/Admin/AdminPage.tsx, client/src/page/Rank/Rank.tsx, client/tailwind.config.js, package.json
> ex: #227 
> 랭킹 페이지 UI 구현
> 리액트 컨페티 효과 추가
> API 설계가 완료되면 그거에 맞게 수정하겠습니다.
> 다른 부분을 건드리지 않아서 바로 PR 하겠습니다
=> [FE] 랭킹 페이지 구현

client/Dockerfile, client/src/api/users/crud.ts, client/src/component/User/SubmitButton.tsx, client/src/component/common/Button.tsx, client/src/page/Profile/ProfilePage.tsx, client/src/page/User/Join.tsx, docker-compose-server.yaml, nestjs-migration/Dockerfile, nestjs-migration/package.json, nestjs-migration/src/app.module.ts, nestjs-migration/src/image/dto/upload-image.dto.ts, nestjs-migration/src/image/image.controller.spec.ts, nestjs-migration/src/image/image.controller.ts, nestjs-migration/src/image/image.module.ts, nestjs-migration/src/image/image.service.spec.ts, nestjs-migration/src/image/image.service.ts, nestjs-migration/src/main.ts, nestjs-migration/src/user/constant/user.constants.ts, nestjs-migration/src/user/entities/user.entity.ts, nestjs-migration/src/user/user.controller.ts, nestjs-migration/src/user/user.repository.ts, nestjs-migration/src/user/user.service.ts
> #304 
- nestJs에 image 모듈 추가
- imageUploadToS3 함수 구현
- client에서 보낸 파일을 S3 버킷에 업로드
- 업로드 끝나면 사진 url을 반환
- 기존에 있는 API들을 건드리기 애매해서 건들지 않음
- 대신, 새로운 API를 추가함
- POST /api/user/check-duplicate 
- body : { nickname? : string, email? : string  }
- 기능 : 입력된 정보들과 일치하는 row가 DB에 있는지 확인
- 둘 중 하나만 입력되도 동작함.
- 원래는 nickname 확인 api와 email 확인 api가 나눠졌으나, 중복 코드가 많아서 하나로 합침.
- res : { isDuplicated : boolean }
- 구현한 API를 회원가입 페이지에 연결함
- 기존에 존재하는 updateUser API를 건드리면 다른 부분도 수정할 일이 생길 것 같아서 API를 2개 추가함.
- 프로필 수정 API 추가
- PATCH /api/user/profile
- body : { nickname? : string, imgUrl? : string  }
- 기능 : 입력된 정보들만 업데이트함.
- 비밀번호 수정API 추가
- PATCH /api/user/password
- body : { originPassword : string, newPassword : string  }
- 기능 : originPassword와 현재 비밀번호의 일치 여부 확인 -> newPassword로 새 비밀번호 생성 후 업데이트
- email, imgUrl 추가 …
=> [FE/BE] Express API to NestJs migration

client/src/api/Rank/rank_crud.ts, client/src/component/Coupon/coupon.tsx, client/src/component/Posts/Rank/UserRank.tsx, client/src/page/Rank/Rank.tsx, shared/community/posts/posts.ts
=> 🐛 [fix] : 랭킹 수정

nestjs-migration/src/post/post.service.ts
=> 🐛 [fix] : 게시글 조회시 조회수 증가하도록 수정

chat_server/package.json, client/package.json, client/postcss.config.cjs, client/src/api/admin/post_crud.ts, client/src/api/admin/user_crud.ts, client/src/component/Admin/UserLog/UserLog.ts, client/src/utils/date-to-str.tsx, consumer-server/package.json, migration-test/package.json, migration-test/tsconfig.build.json, nestjs-migration/package.json, package.json, server/package.json, shared/package.json
CI/CD에 적용하기 위한 코드 포맷 검사 스크립트를 추가하고, 포맷 교정이 필요한 파일에 포맷 교정을 적용합니다.
- 코드 포맷 검사: 포맷 교정이 필요하면 에러 발생(exit code `1`), 필요하지 않으면 정상 종료(exit code `0`)
- `npm run format:check`: 전체 경로 검사
- `npm run format:check:partial -- 경로1 경로2 ...`: 지정한 경로에서만 검사
- 예: `npm run format:check:partial -- client shared`
- 코드 포맷 교정 적용
- `npm run format:write`: 전체 경로 교정
- `npm run format:write:partial -- 경로1 경로2 ...`: 지정한 경로에서만 교정
- 각 워크스페이스(와 shared)에서 포맷 검사/교정을 수행합니다.
- 워크스페이스 루트의 코드 포매팅 스크립트를 재사용하도록 작성했습니다.
- 실행 방법
- (각 워크스페이스 디렉터리에서) `npm run format:동작`
- <mark>**(루트 디렉터리에서) `npm run format:동작 -w 워크스페이스명`**</mark>
- 예: `npm run format:check -w client` → client 워크스페이스 대상으로 코드 포맷 검사 (→ client, shared)
- `--check` 플래그: https://prettier.io/docs/en/cli#--check
- Exit codes: https://prettier.io/docs/en/cli#exit-codes
- …
=> 🚀 [chore] : 코드 포맷 검사 스크립트 추가
