server/db/sql/comments.sql
server/db/sql/posts.sql

#24
`posts`, `post_likes`, `comments`, `comment_likes` 테이블의 `TIMESTAMP` 타입 컬럼이 아래와 같이 자동으로 초기화 또는 갱신되도록 변경합니다.
1. `created_at` 컬럼은 레코드 삽입 시 별도의 값을 전달하지 않았다면 `NOW()`로 초기화됩니다.
2. `updated_at` 컬럼은 레코드 수정 시 별도의 값을 전달하지 않았다면 `NOW()`로 변경됩니다.
- `updated_at` 컬럼에는 `DEFAULT` 구문을 일부러 안 넣었는데, 다른 의견 있으신가요?
- 추후 게시글·댓글의 수정 여부를 `updated_at != null`로 판단하려는 의도입니다.

fix: 게시글, 댓글, 좋아요 테이블 timestamp 컬럼 자동 초기화, 갱신

---

server/controller/comments_controller.ts
server/db/context/comment_context.ts
server/route/comments_router.ts

#22
- comments context에, DB에 새 댓글을 등록하는 내용 구현
- comments controller에 댓글 생성 API 핸들러 구현
- 댓글 생성 API 등록
- `server/db/context/comment_context.ts`에서 에러를 핸들링하는 패턴이 괜찮은지 의견을 부탁드립니다.
- `if ... else if ...`을 일일이 작성하는 것과 고민하다가, 배열을 필터하는 방식으로 구현했는데, `if ... else if ...`가 더 읽기 편하다면 에러 핸들링 구현을 변경하겠습니다.
- 현재 구현상 `post_id` param 유효성 검사를 validator와 controller 양쪽에서 각각 진행하는데, 중복이라 한쪽의 유효성 검사를 제거해야 한다면 controller 쪽에서 `post_id` 유효성 검사를 제거해도 괜찮을까요?
- 이렇게 변경하게 된다면, 이전에 작성한 `GET /api/comment/:post_id` 또한 동일한 방식으로 유효성 검사를 하도록 변경하려고 합니다.
- 그 외 수정이 필요한 부분이나 다른 의견이 있으면 남겨 주세요.

[BE] 댓글 생성 API 구현

---

server/controller/comments_controller.ts
server/db/context/comments_context.ts
server/route/comments_router.ts

#33
일관성을 향상하는 작업은 댓글 API 구현 완료 후에 진행하려 했으나, 작업 시 혼동을 유발하여 먼저 작업했습니다.
- 댓글 수정 API 구현
```jsonc
{
id: number, // 양의 정수
content: string, // 비어 있지 않은 문자열
// 임시 필드: 토큰 검증 미들웨어 구현 후 제거 작업 필요
author_id: number // 양의 정수
}
```
- 댓글 API 일관성 향상
- 잘못 구현된 부분 등, 이상한 부분이 있다면 말씀해 주세요.
- 더 나은 처리 방법, 함수명, request body 구성 등이 있다면 말씀해 주세요.

[BE] 댓글 수정 API 구현 및 댓글 API 일관성 향상

---

server/controller/comments_controller.ts
server/db/context/comments_context.ts
server/route/comments_router.ts

#39
- 댓글 삭제 API 구현
```jsonc
{
id: number, // 양의 정수
author_id: number // 양의 정수 (임시 필드: 토큰 검증 미들웨어 구현 후 제거 작업 필요)
}
```
잘못 구현된 부분, 이상한(이상해 보이는) 부분, 더 나은 처리 방법이나 명명법 등이 있다면 말씀해 주세요.

[BE] 댓글 삭제 API 구현

---

server/controller/users_controller.ts
server/db/context/users_context.ts
server/middleware/auth.ts
server/route/users_router.ts
server/utils/token.ts

- #43
- #46 
- 토큰 발행하는 방식보다 더 적절한 방식 있을까요? 

[BE] 비밀번호 확인 API 구현

---

server/db/context/comments_context.ts

- #50
- `created_at` 컬럼으로만 정렬하면 [동시에 작성된 댓글의 순서는 보장되지 않으므로](https://stackoverflow.com/questions/6662837/how-does-mysql-order-rows-with-the-same-value), `id` 순서로도 정렬해야 합니다.
- 이 내용은 삭제된 댓글의 수정을 방지합니다.
- 댓글 목록 조회에서, `id`가 작성 순서와 일치하니 `id` 순서로 정렬해도 괜찮겠다는 생각도 했으나, 의미가 좀 더 직접적인 `created_at`으로 우선 정렬하도록 작성했습니다. 다른 의견 있으면 말씀해 주세요.

[BE] 댓글 context의 DB 쿼리 보완

---

server/controller/users_controller.ts
server/db/context/token_context.ts
server/db/context/users_context.ts
server/middleware/auth.ts
server/route/users_router.ts

- #42
- 회원가입시 이미 탈퇴한 회원의 이메일 인 경우 일단 에러 처리 해놨는데요. 이 경우에 다른 처리 방법에 대한 아이디어 있을까요?

[BE] 회원 탈퇴 API 구현

---

server/controller/comments_controller.ts
server/route/comments_router.ts
server/utils/validations/comments/comment.ts
server/utils/validations/comments/constants.ts

- #55
- 댓글 API URL 변경
- **(1) 조회** → `GET /api/comment?post_id={}` ... `post_id`를 param에서 query로 옮김
- ~~(2) 등록 → `POST /api/comment` ... 현재 구현 유지~~
- ~~(3) 수정 → `PATCH /api/comment` ... 현재 구현 유지~~
- **(4) 삭제** → `DELETE /api/comment/{comment_id}` ... `comment_id`를 body에서 param으로 옮김
- 댓글 API 유효성 검사를 router에서 추출
- #56 과 같은 구조로 옮겼습니다.
- 잘못되었거나 기타 수정이 필요한 부분 있으면 말씀해 주세요.

[BE] 댓글 API URL 변경 및 유효성 검사 리팩터링

---

server/controller/comments_controller.ts
server/controller/likes_controller.ts
server/controller/posts_controller.ts
server/db/context/comments_context.ts
server/db/context/likes_context.ts
server/db/context/posts_context.ts
server/db/mapper/comments_mapper.ts
server/db/mapper/likes_mapper.ts
server/db/mapper/posts_mapper.ts
server/db/model/comments.ts
server/db/model/likes.ts
server/db/model/posts.ts
server/db/sql/comments.sql
server/db/sql/posts.sql
server/route/likes_router.ts
server/route/route.ts
server/utils/validations/likes/constants.ts
server/utils/validations/likes/like.ts

- #62
- 게시글 좋아요와 댓글 좋아요의 테이블 구조가 동일하여 컬럼명만 바꾸면 그대로 사용할 수 있습니다.
> - 게시글 좋아요
>   - ~~조회: `GET /api/like/post/{post_id}`~~
>   - 활성화: `POST /api/like/post/{post_id}`
>   - 취소: `DELETE /api/like/post/{post_id}`
>   - 응답 본문
>     ```typescript
>     {
>       post_id: number,
>       likes: number,
>       user_liked: boolean // 비로그인 시 항상 false
>     }
>     ```
> - 댓글 좋아요
>   - ~~조회: `GET /api/like/comment/{comment_id}`~~
>   - 활성화: `POST /api/like/comment/{comment_id}`
>   - 취소: `DELETE /api/like/comment/{comment_id}`
>   - 응답 본문
>     ```typescript
>     {
>       comment_id: number,
>       likes: number,
>       user_liked: boolean // 비로그인 시 항상 false
>     }
>     ```
> - 모두 로그인 필요
- 게시글과 댓글 좋아요 테이블이 테이블명(`*_likes`)과 컬럼명 하나(`*_id`) 제외하고는 동일하고 규칙적이어서, 코드 중복을 줄이기 위해 일반화를 했습니다.
- 더 나은(더 …

[BE] 게시글, 댓글 좋아요 API

---

client/src/App.css.ts
client/src/api/posts/crud.ts
client/src/component/Posts/Modal/PostModal.css.ts
client/src/component/Posts/Modal/PostModal.tsx
client/src/component/Posts/Posts.tsx

#68 
- request 함수 추가
- 게시글 생성/수정 modal
- 게시글 수정 기능을 생성 모달에 추가할지, 게시글 내용 페이지에 추가할지 고민하다가 우선은 수정 기능에 추가했습니다.
혹시, 게시글 내용을 보는 페이지에서 수정 기능이 동작하는게 더 나을까요?

[FE] 게시글 생성/수정 모달

---

server/db/context/comments_context.ts
server/db/context/posts_context.ts
server/db/mapper/comments_mapper.ts
server/db/mapper/posts_mapper.ts
server/db/model/comments.ts
server/db/model/posts.ts

- #69
게시글 내용, 댓글 목록 조회 API의 응답에, 해당 게시글, 댓글을 회원이 작성했는지 여부를 boolean으로 나타내는 필드(`is_author`)를 추가합니다. 이 필드는 게시글 내용 페이지에서 게시글과 댓글에 수정, 삭제 버튼을 노출할지 결정하는 데 필요합니다.
- 게시글 내용 조회 API
- 댓글 목록 조회 API
- 구현 방법이 잘못되었거나 수정이 필요한 부분, 수정했으면 하는 부분 있으면 말씀해 주세요.

[BE] 게시글, 댓글 조회 API 응답에 is_author 필드 추가

---

client/src/App.tsx
client/src/api/users/crud.ts
client/src/component/User/User.tsx
client/src/page/User/Login.css.ts
client/src/page/User/Login.tsx
client/src/page/User/User.tsx

- #71
- 사용자 닉네임
- 로그인 시간
- 로그인 여부(boolean)
잘못 구현된 부분이나 이상한 부분 있으면 말해주세요.

[FE] 로그인 화면 구현

---

client/package.json
client/src/App.tsx
client/src/component/Posts/PostInfo.css.ts
client/src/component/Posts/PostInfo.tsx
client/src/component/Posts/Posts.tsx
client/src/page/Posts/PostInfoPage.css.ts
client/src/page/Posts/PostInfoPage.tsx
client/src/utils/date-to-str.tsx
server/db/context/posts_context.ts
shared/index.ts
shared/posts/mappers.ts
shared/posts/models.ts

게시글 정보 컴포넌트 하나 완성하는데 너무 많은 변경이 필요해 보여서 한 번 끊어서 올립니다.
- 게시글 정보 컴포넌트 추가
- 게시글 목록에서 게시글을 클릭 -> navigate("post/:id")만 동작하면 되도록 구현함.
- 따라서 param = id
- 해야할 일
- 컨벤션을 잘 못 지킨 부분이 있을까요?
- 혹시 구현 상, 미흡한 부분이 있다면 알려주세요!

[FE] 게시글 정보 컴포넌트

---

client/src/page/Posts/PostInfoPage.tsx

IPostInfo 타입의 변수에 is_author을 추가했습니다.

fix : IPostInfo에 is_author가 추가되어 발생한 타입 오류 수정

---

client/src/App.css
client/src/App.tsx
client/src/component/Posts/PostList/PostList.css.ts
client/src/component/Posts/PostList/PostList.tsx
client/src/component/common/Pagination/Pagination.css.ts
client/src/component/common/Pagination/Pagination.tsx
client/src/component/common/SearchForm/SearchForm.css.ts
client/src/component/common/SearchForm/SearchForm.tsx
client/src/hook/useMainPageSearchParams.ts
client/src/page/Main/Main.css.ts
client/src/page/Main/Main.tsx
client/src/utils/clamp.ts

- #77
- #87
- **인덱스 페이지(`/`)를 게시글 목록 페이지로 교체하고, 기존 `<TestMain>` 컴포넌트는 계속 접근 가능하도록 `<Main>` 페이지 컴포넌트 안으로 옮겼습니다.**
- 아래 2가지는 작동을 확인할 수 없는데, 서버 코드 수정이 필요합니다.
- 조회수 표시: 게시글 목록 응답에 포함되어 있지 않아서 일단 자리만 만들어 두었습니다.
- 조회수순 정렬: 서버에서 쿼리스트링 파싱 시 NaN 처리 문제로 확인됩니다.
- 잘못 구현되었거나 수정 필요한 부분 있으면 말씀해 주세요.

[FE] 메인 페이지(게시글 목록) 컴포넌트 구현

---

server/db/context/posts_context.ts
shared/posts/enums.ts
shared/posts/mappers.ts

#87
- SortBy의 기본값을 아래와 같이 수정했습니다.
- 기존 : VIEWS = 0, LIKES = 1
- 수정 : VIEWS = 1, LIKES = 2
- PostHeader의 field에 조회수(views)를 추가했습니다.

fix : 조회수 기준 정렬 버그 + post_header field에 views 추가

---

client/src/App.tsx
client/src/api/users/crud.ts
client/src/component/Header/Header.css.ts
client/src/component/Header/Header.tsx
client/src/page/User/Login.tsx

- #90
- 로그인 안했을 시
- 로그인 했을시
- 버튼들을 아이콘으로 해봤는데요. 글씨로 쓰는게 나을까요 아이콘이 나을까요

[FE] 사이트 헤더 구현

---

client/src/App.tsx
client/src/api/users/crud.ts
client/src/page/User/ProfileUpdate.css.ts
client/src/page/User/ProfileUpdate.tsx
client/src/page/User/User.tsx
server/controller/users_controller.ts
server/middleware/auth.ts

- #97 
- 원래 계획은 버튼눌렀을때 회원정보가 보이고 수정버튼 눌러서 변경하게끔 할 계획이었지만 저희가 받은정보가 이메일이랑 닉네임 2개에 바꿀 수 있는거는 닉네임 뿐이라 구성 상 별로라고 느껴져서 해당 이미지처럼 변경했습니다. 다른 아이디어 있으시면 말씀해주세요.

[FE] 회원정보 수정 페이지 추가

---

client/src/api/comments/crud.ts
client/src/component/Comments/CommentItem/CommentItem.css.ts
client/src/component/Comments/CommentItem/CommentItem.tsx
client/src/component/Comments/CommentLikeButton/CommentLikeButton.css.ts
client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
client/src/component/Comments/Comments.css.ts
client/src/component/Comments/Comments.tsx
client/src/page/Posts/PostInfoPage.tsx
server/db/context/comments_context.ts
shared/comments/mappers.ts
shared/comments/models.ts
shared/index.ts

- #91 : 작업이 길어져서 기본적인 부분(읽기) 먼저 반영하고자 합니다.
- 댓글 항목 컴포넌트
- 댓글 좋아요 컴포넌트
- 댓글 수정·삭제 버튼
- 댓글 수정 폼
- 댓글 목록 컴포넌트
<details><summary>🖼️ 댓글 렌더 예시 + 좋아요 유무 비교 (아래가 좋아요 누른 상태)</summary>
> <img width="600" alt="comment_comparison" src="https://github.com/user-attachments/assets/9371c7e9-88d3-4dd1-92b2-2ae5715a3a86">
</details>
<details><summary>🖼️ 회원 본인의 댓글에는 수정, 삭제 버튼을 표시</summary>
> <img width="600" alt="comment_mine" src="https://github.com/user-attachments/assets/fcb35656-505f-48d6-a68f-9e5a5f822f1d">
</details>
<details><summary>🖼️ 댓글 수정 토글: 댓글 수정 모드</summary>
> <img width="600" alt="comment_edit" src="https://github.com/user-attachments/assets/efbe7ce8-0f38-4176-a5c2-2a246841e149">
</details>
- 저의 우선순위 설정 미숙으로 작업이 늘어져서, 일단 기본적인 부분(읽기) 먼저 반영하고자 합니다.
- 잘못된 부분이나 수정 필요한 부분 있으면 말씀해 주세요.

[FE] 댓글 목록 컴포넌트 기본 구조, 댓글 목록 읽기

---

client/src/api/likes/crud.ts
client/src/component/Comments/CommentForm/CommentForm.css.ts
client/src/component/Comments/CommentForm/CommentForm.tsx
client/src/component/Comments/CommentItem/CommentItem.css.ts
client/src/component/Comments/CommentItem/CommentItem.tsx
client/src/component/Comments/CommentLikeButton/CommentLikeButton.tsx
client/src/component/Comments/Comments.css.ts
client/src/component/Comments/Comments.tsx

- #91
- #101
PR #101 에 이어서, 클라이언트에서의 댓글 작성, 수정, 삭제와 댓글 좋아요/취소를 구현합니다.
- 댓글 항목 컴포넌트
- 댓글 좋아요 컴포넌트
- 댓글 수정 폼
- 댓글 삭제
- 댓글 목록 컴포넌트
다른 UI 부분은 #101 과 유사합니다.
- 잘못 구현된 부분이나 수정이 필요한 부분 있으면 말씀해 주세요.

[FE] 댓글 작성, 수정, 삭제, 좋아요

---

client/src/component/Posts/PostList/EmptyPostListBody.tsx
client/src/component/Posts/PostList/PostList.css.ts
client/src/component/Posts/PostList/PostList.tsx
client/src/page/Main/Main.tsx
client/src/utils/date-to-str.tsx
shared/posts/models.ts

- #92
- 게시글 목록에서 특수한 상황 처리
- 같은 날이면 연월일 생략 -> `HH:mm:ss`
- 같은 해면 연도 생략 -> `MM.DD HH:mm` 또는 `MM.DD`
- 다른 해면 시각 생략 -> `YYYY.MM.DD`
> ![no-post](https://github.com/user-attachments/assets/d4d41c53-7e6a-44be-bd5c-ef0fab57ae5a)
> ![no-search](https://github.com/user-attachments/assets/01e1862d-5a08-4416-871f-f5fc49e06cb1)
> ![load-failed](https://github.com/user-attachments/assets/44a21df6-363a-4475-ab24-ff22eecb0c8f)
- 잘못 구현되었거나 수정 필요한 부분이 있으면 말씀해 주세요.
- 작업 내용에 대해서 다른 의견 있으면 말씀해 주세요.

[FE] 메인 페이지의 게시글 목록 정보 보충

---

client/src/App.css.ts
client/src/App.tsx

- #105 
<details>
<summary>🖼️로그인 화면</summary>
</details>
<details>
<summary>🖼️회원가입 화면</summary>
</details>
<details>
<summary>🖼️비밀번호 확인 화면</summary>
</details>
<details>
<summary>🖼️유저정보 수정 화면</summary>
</details>

[FE] 회원 관련 화면 레이아웃 중앙 정렬 구현

---

server/db/context/posts_context.ts

#108
- ID가 `post_id`인 게시글 조회 성공 시
https://github.com/user-attachments/assets/d47b26ff-6e29-4bca-b1d1-a92cc9d2553d
- 현재는 SELECT 문과 UPDATE 문을 사용하여 DB에 2번 접근하는데, 더 좋은 방법이 있을까요?

feat : 게시글 내용 조회 기능에  조회수 증가 로직 추가

---

client/src/App.tsx
client/src/api/api.ts
client/src/api/errors.ts
client/src/api/users/utils.ts
client/src/component/Comments/CommentItem/CommentItem.tsx
client/src/component/Comments/Comments.tsx
client/src/component/Posts/Modal/PostModal.tsx
client/src/component/utils/ErrorModal.css.ts
client/src/component/utils/ErrorModal.tsx
client/src/state/errorModalStore.ts

#73 
- ApiCall 함수 추가
- 이유
- http request 의 error 상황을 handling하는 로직을 각자 구현해야 하는 것이 불편했다.
- 하지만, httpRequest 함수에서 에러 처리하는 로직을 다 구현하면 코드가 길어져서 가독성이 떨어진다.
- 따라서 api 요청 error 상황을 handling하는 함수를 추가 구현하기로 했다.
- 사용 방법
- 기존
```ts
const createPost = async() => {
const body = {~~};
sendCreatePostRequest(body).then((res)=>{
if(res.status >= 400){
console.log(res);
return;
}
});
};
```
- 바뀐 사용법
```ts
const createPost = async() => {
const body = {
title,
content
};
await ApiCall(()=>sendCreatePostRequest(body));
};
```
- return 값을 사용할 경우
```ts
// 특별히 에러 처리 안 할 경우
const res = await ApiCall(()=>sendCreatePostRequest(body));
if(res){
return;
} // -> 이후 원하는 로직 작성
// 에러 일 때, 특별 처리를 하는 경우
const errorHandle = () => { /* 원하는 로직 작성 */ };
const res = await ApiCall(()=>sendCreatePostRequest(body), …
```

[FE] httpRequest의 error handling 함수 추가

---

client/src/api/api.ts
client/src/component/Header/Header.tsx
client/src/page/User/CheckPassword.tsx
client/src/page/User/Join.tsx
client/src/page/User/Login.tsx
client/src/page/User/ProfileUpdate.tsx

- #115 
- #116 
- api.ts에 수정한부분이 있습니다. 따로 api.ts부분 수정하신 부분이 있다면 충돌이 날 수 있습니다.
- 괜찮으시다면 #116 이슈에 지금 PR을 연결하겠습니다.

[FE] 유저 API에 에러 핸들링 함수 적용

---

client/src/App.tsx
client/src/component/Chats/ChatRooms.tsx
client/src/component/Chats/ChatRooms/ChatRooms.css.ts
client/src/component/Chats/ChatRooms/ChatRooms.tsx
client/src/component/Chats/ChatRooms/Rooms/Rooms.css.ts
client/src/component/Chats/ChatRooms/Rooms/Rooms.tsx

- 비밀방을 위한 디자인 수정 후 UI 추가
- 테스트를 위해 임시 데이터를 생성
디자인에서 크게 2개의 단위로 나누어 작업했습니다.
- 채팅방 검색(search)
- 서버에 채팅방 keyword 전달 (기능 미구현, alert: keyword: '내용' 채팅방 검색)
- 검색된 채팅방 리스트 표시 (검색된 상태인 조건으로 임시 채팅방 검색 리스트 표시)
- 채팅방 생성(create room)
- 채팅방 생성 모달을 엶 (기능 미구현, alert: 채팅창 모달)
- 채팅방 이동
- 채팅방 클릭시 해당 채팅방(aside)으로 이동(테스트로 room/1로 이동)
- 비밀 방일 시 비밀번호 입력 모달 엶 (기능 미구현, 테스트로 room/1로 이동)
- 각 채팅방 별 요소
- 채팅방 이름(room title)
- 비밀 채팅방 유무(private room)
- 채팅방 참가 인원(participants num)
- 채팅방에 대한 pagination 구현 예정
- 내가 참여한 채팅방 리스트
- 검색을 통한 리스트 나열을 제외하곤 채팅방 검색 리스트와 같음
- 채팅방 이동
- 채팅방 검색과 같음
- 검색 채팅방 요소에서 2가지 요소 추가
- 접속 인원(cur num)
- 최근 메시지(last message)
- 채팅방에 대한 pagination 구현 예정
1. 검색 채팅방과 내 채팅방을 분리하여 컴포넌트화 하는게 좋을까요?
2. 채팅방 리스트에서 채팅방을 컴포넌트화 하는게 좋을까요?

검색 채팅방 리스트 & 내 채팅방 리스트(채팅 aside) UI 추가

---

client/src/component/Chats/ChatRooms/ChatRooms.tsx
client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
client/src/component/Chats/ChatRooms/Pagenation/pagenation.css.ts

- 채팅방에 대한 pagination 추가
- perPage는 2개
- 임시 데이터로 검색된 결과가 있다는 가정하에 기능 구현
💬 리뷰 요구사항(선택)
- 추후에 채팅방 리스트 페이지에서 search room list와 my room list를 모듈화하려고하는데,
pagination 컴포넌트를 rooms 컴포넌트에 추가하는게 맞을까요?

채팅방 리스트 pagination 추가

---

server/controller/admin_controller.ts
server/db/context/users_context.ts
server/db/mapper/users_mapper.ts
server/db/model/users.ts
server/db/sql/users.sql
server/route/admin_router.ts
server/route/route.ts

- #128
-   [x] `GET /api/admin/user?index={}&perPage={}&nickname={}&email={}` 엔드 포인트 추가
-   [x] 가입일 유저 스키마에 추가
-   [x] pagination 기능 추가
-   [x] 닉네임, 이메일 검색 기능 추가
가입일 추가하실때
```sql
ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW()
```
이 sql 문 사용하시면 될거 같습니다.

[BE] 어드민용 사용자 목록 조회 API 구현

---

server/controller/admin_controller.ts
server/db/context/users_context.ts
server/route/admin_router.ts
server/utils/validations/admin/admin.ts
server/utils/validations/admin/constants.ts

[BE] 사용자 계정 삭제/복구 API 구현

---

server/controller/admin_controller.ts
server/db/context/posts_context.ts
server/db/mapper/posts_mapper.ts
server/db/model/posts.ts
server/db/sql/posts.sql
server/route/admin_router.ts

- #136
is_private coloum추가 하실 때
``` sql
ALTER TABLE posts ADD COLUMN is_private Boolean NOT NULL DEFAULT FALSE
```
이 sql 문 사용하시면 될거 같습니다.

[BE] 게시글 목록 조회 API 구현

---

.gitignore
chat_server/app.ts
chat_server/config/kafka_config.ts
chat_server/config/redis_config.ts
chat_server/index.ts
chat_server/package.json
chat_server/services/kafka_service.ts
consumer-server/src/config/dbConfig.ts
consumer-server/src/config/kafkaConfig.ts
consumer-server/src/index.ts
consumer-server/src/models/chatMessageModel.ts
consumer-server/src/services/kafkaService.ts
consumer-server/src/services/messageService.ts
docker-compose.yaml
server/db/sql/chats.sql
shared/chats/dto.ts

- #132 
resolved #132 
1. 메시지 수신 시 Kafka로 송신은 추후 소켓 구현 이후 구현 예정입니다. ( 메시지 송신 부분은 구현 완료 )
2. 서버 장애시 처리는 MVP 구현 이후 구현 예정입니다.
3. chat_server에 test 부분 지우시거나 주석처리하시고 작업 바랍니다.
4. erd 수정되었습니다. `server/db/sql/chats.sql` 확인하시고 적용해주세요.
5. 카프카 설정 변경이 있어습니다. 다시 설정해주세요.
1. 프로젝트 루트로 이동
2. 컨테이너 중지 : `docker stop kafka-kraft-1 kafka-kraft-2 kafka-kraft-3 redis kafka-ui`
3. 컨테이너 삭제 : `docker rm -v kafka-kraft-1 kafka-kraft-2 kafka-kraft-3 redis kafka-ui`
4. 프로젝트에서 디렉토리 삭제 ( logs )
6. 컴포즈 올리기 : `docker-compose -f docker-compose.yaml up -d`
7. 토픽 생성 (바로 실행하면 오류 있습니다. 올라간 컨테이너 실행 중인지 확인하고 진행해주세요.)
```powershell
docker-compose exec kafka-kraft-1 `
kafka-topics --create `
--topic chat `
--partitions 1 `
--replication-factor 2 `
--if-not-exists `
--bootstrap-server kafka-kraft-1:9092
```
```bash
docker-compose …
```

[BE] 메시지 큐 구현

---

.gitignore
client/src/component/Chats/ChatRooms/SearchedChatRooms.tsx
server/controller/chats_controller.ts
server/db/context/chats_context.ts
server/db/sql/chats.sql
server/route/chats_router.ts
shared/chats/dto.ts
shared/chats/mappers.ts
shared/chats/message.ts

> ex: #이슈번호, #이슈번호
- 채팅방에 입장했을 때, 이전 메세지 기록들을 불러오는 api입니다.
- 우선은 Postman으로 구현 확인했습니다.
- client에서는 다른 기능들 구현 한 이후에 만들겠습니다.
- 한 분이라도 보시면 머지하겠습니다.

[채팅] 메세지 기록 조회 API

---

server/controller/chats_controller.ts
server/db/context/chats_context.ts
server/route/chats_router.ts
shared/chats/chat-room.ts

- 가입에 사용하는 데이터 수정
- 기존의 Request에 content, isPrivate를 추가함
```ts
export interface IJoinRoomRequest {
roomId: number; // 가입 할 채팅방 번호
content: string; // socket에서 생성한 가입 축하 인사, 이 대신 nickname 보내도 됨
isPrivate: boolean; // 비밀 방 여부
password: string; // 방 비밀번호 (null 허용)
}
```
- 따라서 socket에서 이 api를 사용하기 위해서는 content도 보내야 함
- content는 가입 축하 인사 : `${nickname}님이 방에 들어왔습니다.`

[채팅] 채팅방 가입 기능 api

---

server/controller/chats_controller.ts
server/db/context/chats_context.ts
server/route/chats_router.ts
shared/chats/dto.ts
shared/chats/mappers.ts

- 채팅방 멤버 dto, mapper함수 추가
```ts
export interface IRoomMembers {
// key = roomId
// value = room member의 id list
[key: number]: number[];
}
```
- 채팅방 별 멤버 id list 반환 api
- 사용 시기 : socket server 동작 시, 채팅방 별 멤버 id list를 받아와서 redis에 저장할 때 사용함.
- 기타 의견 있으면 말씀해주세요

[채팅] 채팅방 별 멤버 리스트 조회 api

---

server/controller/admin_controller.ts
server/db/context/posts_context.ts
server/route/admin_router.ts
server/utils/validations/admin/admin.ts
server/utils/validations/admin/constants.ts
server/utils/validations/posts/posts.ts
server/utils/validations/users/user.ts

- #140
- 게시물 비공개와 관련된 기능은 추후에 인화님하고 의견 나누어 본 후에 추가하도록 하겠습니다.

[BE] 관리자용 게시물 삭제/복구 및 공개/비공개 API 구현

---

server/controller/admin_controller.ts
server/db/context/stats_context.ts
server/db/model/stats.ts
server/route/admin_router.ts
server/utils/validations/admin/admin.ts

- #169
- 전체 통계 데이터 쪽에서는 게시글 삭제했을 때 게시글에 쓴 댓글도 통계에 포함되지 않게 했는데요.
유저별 통계 에서도 포함되지 않게 할까요?
- 삭제된 데이터도 포함되게 하고 싶으시면 말씀해주세요.

[BE] 유저별 통계 데이터 API 구현

---

server/controller/oauth_controller.ts
server/route/oauth_router.ts
server/utils/oauth/constants.ts
server/utils/oauth/oauth.ts
server/utils/validations/oauth/oauth.ts

- #157
소셜 로그인으로 가입한 계정의 정보 수정 및 탈퇴 기능 사용을 위해, 비밀번호 재확인 대신 소셜 로그인 재확인 관련 API를 구현합니다.
- 기존 OAuth 로그인 처리 API 재사용 (Authorization code → OAuth access token → OAuth 회원번호 조회)
- 해당 provider, 회원번호를 연동한 유저의 이메일, 비밀번호 등록 여부에 따라서
- 메서드: `GET`
- 엔드포인트: `/api/oauth/reconfirm-url/{provider}`
- Params
- provider: `google | kakao | naver`
- 메서드: `POST`
- 엔드포인트: `/api/oauth/reconfirm`
- Request body
```typescript
{
"provider": "google" | "kakao" | "naver",
"code": string
}
```
1. `GET /api/oauth/reconfirm-url/{provider}` 요청으로 OAuth 서비스 제공사별 로그인 재확인 URL 조회
2. 조회한 URL을 웹 브라우저에서 접속하고 로그인 재확인 절차 진행
3. 로그인 후 돌아오는 페이지의 주소에서 `code` 파라미터의 값 복사
- DevTools 콘솔에서 `new URLSearchParams(location.search).get('code');`
4. `POST /api/oauth/reconfirm` 요청 (아래는 요청 본문)
```typescript
{
"provider": "google" | "kakao" | "naver", …
```

[BE] 소셜 로그인 재확인 관련 API 구현

---

client/src/component/Chats/ChatRooms/ChatRooms.tsx
client/src/component/Chats/ChatRooms/MyChatRooms.tsx
client/src/component/Chats/ChatRooms/Pagenation/Pagenation.tsx
client/src/state/ChatRoomStore.ts

- zustand state 추가
```ts
// 실제 local storage에 저장되는 데이터들
interface IChatRoomState {
myRoomInfo: RoomsInfo;
chatRoomMessageLogs: Map<number, IMessage[]>;
}
```
- 엥? IRoomInfo가 뭐에요?
- 내 채팅방을 불러온 후, 페이지네이션을 통해 채팅방 목록을 보여주기 위한 타입입니다.
```ts
export interface RoomsInfo {
totalRoomCount: number;
rooms: {
[key: number]: IRoomHeader[];
};
// key : 현재 page
// values : 현재 page에서 보여 줄 채팅방 정보
}
```
- storage에 저장하기 위한 actions
- api 요청 결과, 불러온 채팅방 리스트를 저장
```ts
setMyRoomInfo: (
totalRoomCount: number,
currentPage: number,
roomHeaders: IRoomHeader[]
) => void;
```
- 불러온 채팅방의 메세지 기록을 저장
```ts
setMessageLogByRooms: (roomId: number, messageLogs: IMessage[]) => void;
```
- 메세지 보낸 후, 메세지 기록에 추가
```ts
updateMessageLogByRoom: (roomId: number, message: IMessage) => void;
```
- 실제 state 를 활용하도록 기존 코드 수정
- 이번 …

[채팅] 채팅 기능을 위한 zustand state와 실제 적용

---

chat_server/app.ts
chat_server/events/chatroom_events.ts
chat_server/events/message_events.ts
chat_server/index.ts
chat_server/package.json
chat_server/services/api_service.ts
chat_server/services/kafka_service.ts
client/.eslintrc.cjs
client/src/App.tsx
client/src/component/Chats/ChatRoom/ChatRoom.tsx
client/src/component/Header/Header.tsx
client/src/state/store.ts
shared/chats/dto.ts
shared/chats/mappers.ts

- #179 
- #180 
- #184 
resolved #179  #180 #184 
1. 메시지 로그 API에서 message가 불러오지 않는 문제가 있습니다. 코드에서 잘못된 부분이 있을까요?
2. db mapper 함수에서 isSystem이 정수로 불려와서 수정한 코드가 있습니다. 수정해도 괜찮을까요?
3. 쿠키의 토큰은 decode만 했습니다.
4. 캐싱 기능은 아직 추가하지 않았습니다.
5. 테스트 방법
1. client/.env: `VITE_CHAT_ADDRESS='http://localhost:3000'` 추가
2. docker에 kafka 동작 확인
3. `npm build --workspace=client`
4. `npm run dev --workspace=server`
6. `npm run dev --workspace=chat_server`
7. `npm run dev --workspace=consumer-server`
8. db rooms에 데이터 추가해주세요.
- 예시
9. db members에 데이터 추가해주세요.
- 예시
10. 서로 다른 브라우저(저는 웨일, 크롬으로 테스트했습니다.)에서 로그인 후 테스트

[FE/BE] 채팅방 입장 및 실시간 채팅

---

chat_server/app.ts
chat_server/events/chatroom_events.ts
chat_server/utils/api.ts
client/src/component/Chats/ChatRooms/ChatRooms.tsx
client/src/component/Chats/ChatRooms/MyChatRooms.tsx
consumer-server/package.json
consumer-server/src/index.ts
server/controller/chats_controller.ts
server/db/context/chats_context.ts
server/db/sql/chats.sql
shared/chats/chat-room.ts

- 메세지 관련 로직(함수, sql, DB column)에서 content , message가 혼용되어 사용됨
- 따라서 content -> message로 수정함
- chat_server
- app.ts : dotenv가 명시되지 않아서 process.env에서 값을 읽어오지 못해 이를 추가함.
- 참고!
- env파일에 환경변수를 제대로 정의했는데도 undefined로 읽히던 문제가 있었음!
- 이유 분석
- 각 프로젝트의 index.ts 또는 app.ts같이 서버를 실행시키기 위한 파일과 같은 위치에 .env 파일을 생성함
- 하지만, package.json에서 정의한 script를 사용해서 서버를 실행시킴
- 이 때, env파일을 package.json과 같은 위치에 있어야 제대로 읽어짐
- 즉, 파일을 실행시키는 명령어를 내리는 디렉토리 위치에 env가 있어야 함!
- chat_server
- api_server로 cookie를 전송함 (header에 추가함)
- client로부터 currentPage를 받음 (해당 페이지에 속하는 채팅방 리스트를 가져오기 위함)
- client
- currentPage 변화에 따라 해당 페이지의 채팅방 리스트를 가져오도록 변경
- (1) 채팅방 aside 진입 시, page=1의 채팅방 리스트 불러오기 이벤트 (get_rooms) 발생
- (2) get_rooms로 가져온 데이터를 zustand state 및 local storage에 저장
- (3) 이후, 리렌더링해서 사용자에게 잘 보이게 함
- (4) 다른 page 클릭 시, 다시 해당 페이지에 대한 채팅방 …

[채팅-FIX] 여러 문제점 수정 

---

client/src/App.tsx
client/src/component/common/Loader/Loader.css.ts
client/src/component/common/Loader/Loader.tsx
client/src/page/OAuthRedirectHandler.tsx
client/src/page/error/NotFound.css.ts
client/src/page/error/NotFound.tsx

- #189 
- 소셜 로그인 처리 중 로딩 화면을 구현했습니다. 
- 404 페이지를 구현했습니다. 
- 로딩 화면
- 404 페이지
파일 경로가 적절한지, 잘못된 사항이 있는지 확인해 주세요.

[FE] 로딩 화면, 404 페이지 구현

---

server/controller/oauth_controller.ts
server/controller/users_controller.ts
server/db/context/oauth_context.ts
server/db/mapper/oauth_mapper.ts
server/db/model/oauth.ts
server/db/sql/oauth.sql
server/utils/oauth/constants.ts
server/utils/oauth/oauth.ts
server/utils/validations/oauth/constants.ts
server/utils/validations/oauth/oauth.ts

- #158
- #157
- #172
&nbsp;
- 연동 해제 여부를 나타내는 `isDelete` 컬럼 추가 (해당 소셜 계정을 다른 유저에게 재연동하지 못하도록)
- OAuth refresh token 컬럼 추가
- 연동 없음: 탈퇴 진행 (분기 처리가 없다는 점을 제외하면 현재 구현과 동일)
- 평소 소셜 로그인: `state`를 `login_type=login`으로 세팅
- 소셜 로그인 재확인: `state`를 `login_type=reconfirm`으로 세팅
&nbsp;
```sql
ALTER TABLE oauth_connections
ADD COLUMN oauth_refresh_token TEXT NULL,
ADD COLUMN isDelete Boolean NOT NULL DEFAULT FALSE;
```
- 위 내용을 실행하면 바로 세팅 가능하지만, 구글로 로그인한 유저의 회원 탈퇴를 바로 진행할 수는 없습니다.
- 구글은 첫 연결 때만 리프레시 토큰을 전달합니다.
- 구글로 로그인한 유저의 회원 탈퇴를 테스트하려면,
1. “Google 계정 관리 → 보안 → [서드 파티 앱 및 서비스 연결](https://myaccount.google.com/connections)”에서 테스트 앱의 연결 끊기
2. 커뮤니티 로그인 페이지에서 다시 구글로 로그인 (OAuth 리프레시 토큰 발급)
3. 회원 탈퇴 기능 테스트
&nbsp;
- #172 와 비슷한 방법으로 기능 확인 가능합니다.
&nbsp;
- 일단 유저에게 한 번 연동한 소셜 계정은 그 유저에게만 재연동 가능하도록 구현했습니다. 다른 의견 있으면 …

[BE] 회원 탈퇴 시 소셜 로그인 연동 해제

---

client/src/component/User/DuplicationCheckButton.tsx
client/src/component/User/EmailForm.tsx
client/src/component/User/InputField.tsx
client/src/component/User/InputForm.tsx
client/src/component/User/NicknameForm.tsx
client/src/component/User/PasswordForm.tsx
client/src/component/User/SubmitButton.tsx
client/src/component/User/css/InputField.css.ts
client/src/component/User/css/SubmitButton.css.ts
client/src/page/User/Join.tsx
client/src/page/User/Login.tsx
client/src/page/User/ProfileUpdate.tsx
client/src/page/User/constants/constants.ts

#206
- 비밀번호 규칙 (힌트) placeholder로 보여주기
- 닉네임, 이메일 폼에 각각 중복 확인 버튼 추가
- 4개의 폼의 검증이 끝나야 회원 가입 버튼이 apply되도록 수정
- 가시적으로 폼 검증 상태 보여주도록 함.
- 로그인 폼, 프로필 업데이트 폼에서의 빌드 에러 수정
- API 사용은 next.js 마이그레이션 이후 작업할 예정입니다!

[Feature] 회원 가입 page 고도화

---

client/package.json
client/src/index.css
client/vite.config.ts

- #215
- 라이트모드에서 일부 콘텐츠가 보이지 않는 문제를 임시로 해결합니다.
- 클라이언트 단의 변경사항을 감지하여 자동으로 빌드하여, 수정 시마다 결과를 확인하기 위해 다시 빌드하는 번거로움을 줄입니다.
- `development` 모드로 자동 빌드를 수행하여, 문서 구조 파악과 디버깅을 용이하게 합니다. (HTML 엘리먼트의 class 이름이 온전히 표시됩니다.)
- `color-scheme` 속성에서는 light를 주석 처리했고, `prefers-color-scheme: light` 미디어 쿼리는 제거했습니다. 삭제한 미디어 쿼리 부분 전체를 주석으로 남겼으면 좋겠다거나, 미디어 쿼리에서 중괄호 내부만 삭제했으면 좋겠다거나, 기타 다른 의견 있으면 말씀해 주세요.
- `watch` 스크립트는 HMR이 적용되지 않아서, 빌드 후 수동으로 새로고침을 해 주어야 하는데 괜찮은가요?

[FE] 라이트모드 스타일 임시 제거 및 클라이언트에 watch 스크립트 추가

---

chat_server/Dockerfile
chat_server/app.ts
chat_server/index.ts
chat_server/utils/api.ts
client/Dockerfile
client/vite.config.ts
consumer-server/Dockerfile
consumer-server/src/config/dbConfig.ts
consumer-server/src/index.ts
docker-command.sh
docker-compose-server.yaml
nginx/default.conf
nginx/nginx.conf
server/Dockerfile
server/app.ts
server/db/connect.ts
server/utils/token.ts
shared/package.json

#209
- 아키텍쳐 수정
> 흰 박스는 docker container를 의미함 
> <img width="600" alt="스크린샷 2024-09-12 오후 11 27 43" src="https://github.com/user-attachments/assets/658acb42-b569-4a9a-b817-348d5ea7c95b">
> [미리캔버스 주소](https://www.miricanvas.com/v2/design/13incan)
- static 파일 요청 시, react build 파일 제공 (web server 역할)
> 실제 코드
```
location / {
root /usr/share/nginx/html;
index index.html;
try_files $uri $uri/ /index.html;
}
```
- 서버 연결 요청을 관리 (proxy server 역할)
> 실제 코드
```
location /api {
proxy_pass http://api-server:9000;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
location /socket.io {
proxy_pass http://chat-server:3000;
proxy_http_version 1.1;
proxy_set_header Upgrade …
```

✨ [feat] DOCKER + NGINX 통합 배포

---

sql/09_role_permission.sql

- #203
- role_permission 테이블이 생성시 오류가 발생하여 그 뒤의 테이블이 생성되지 않던 오류 수정
- PRIMARY KEY 정의에서 잘못된 'ON DELETE CASCADE' 구문 제거
- 프로젝트 db세팅하고 관련된 사항인거같아서 전체 팀원에게 reviewers를 남겼습니다.

🐛 [fix] : role_permission 테이블 생성 안되는 오류 수정

---

client/src/App.tsx
client/src/api/users/crud.ts
client/src/api/users/oauth.ts
client/src/component/Header/DropdownMenu.tsx
client/src/component/User/OAuthLoginButtons.tsx
client/src/component/User/css/OAuthLoginButtons.css.ts
client/src/page/OAuth/OAuthLink.css.ts
client/src/page/OAuth/OAuthLink.tsx
client/src/page/OAuth/OAuthRedirectHandler.tsx
shared/community/users/users.ts
shared/community/users/users_mapper.ts
shared/index.ts

- #214
<br>
- 프로바이더별 소셜 로그인 여부에 따라
<br>
> <img width="160" alt="oauth-dropdown" src="https://github.com/user-attachments/assets/8a544994-b924-493a-aca7-1a3d89f94e15">
> <img width="460" alt="oauth-management" src="https://github.com/user-attachments/assets/e729a51f-d710-44d0-9370-fcece9b4ec87">
<br>
- UI 디테일은 UI 수정 작업을 진행할 때 한번에 정리하려 하는데 괜찮은가요?
- 잘못 구현되어서 수정이 필요한 부분이나, 그 외에도 변경했으면 하는 부분 있으면 말씀해 주세요.

[FE] 소셜 로그인 연동 추가/해제

---

client/src/App.tsx
client/src/component/Header/DropdownMenu.tsx
client/src/component/Header/Header.tsx
client/src/hook/useStringWithValidation.ts
client/src/page/OAuth/OAuthLink.css.ts
client/src/page/OAuth/OAuthLink.tsx
client/src/page/OAuth/OAuthRedirectHandler.tsx
client/src/page/User/CheckPassword.css.ts
client/src/page/User/CheckPassword.tsx
client/src/page/User/EmailRegistration.tsx
client/src/page/User/Join.css.ts
client/src/page/User/Join.tsx
client/src/page/User/Login.css.ts
client/src/page/User/Login.tsx
client/src/page/User/ProfileUpdate.css.ts
client/src/page/User/ProfileUpdate.tsx
client/src/state/store.ts
server/db/context/users_context.ts

- #214
<br>
- 이메일을 등록하지 않은 유저에게만 이메일 필드 노출 (즉, 최초 1회만 이메일 등록 가능)
- 이메일 중복 발생 시 Express 서버가 아예 죽어 버려서 일단 수정했습니다.
<br>
https://github.com/user-attachments/assets/077072f9-863a-4839-99d3-2cf97c6e67ed
<br>
- 잘못 구현되어서 수정이 필요한 부분이나, 그 외에도 변경했으면 하는 부분 있으면 말씀해 주세요.

[FE] 소셜 로그인 가입 유저의 이메일 등록

---

nestjs-migration/src/post/dto/delete-post.dto.ts
nestjs-migration/src/post/dto/get-post-headers.dto.ts
nestjs-migration/src/post/dto/update-post.dto.ts
nestjs-migration/src/post/entities/post.entity.ts
nestjs-migration/src/post/post.controller.spec.ts
nestjs-migration/src/post/post.controller.ts
nestjs-migration/src/post/post.module.ts
nestjs-migration/src/post/post.repository.ts
nestjs-migration/src/post/post.service.spec.ts
nestjs-migration/src/post/post.service.ts

* #248 
* #235 
1. (코드오류수정) 게시물 조회: 쿼리 파라미터 keyword 적용 안되는 오류 ⇒ new Bracket를 추가해서 수정
2. (sql문 삭제) 게시물 생성 및 업데이트 findOne-author 코드삭제: 로그인 가드로 검사하므로 필요없는 조건이라 생각하여 삭제
3. new object.assign 리팩토링
4. update where 조건에 빼먹은 authorId 추가
게시물 조회 시 likes string으로 나옴 
`likes: "0"`
-> 이 부분 아직 해결을 못했습니다.

[BE] 게시물 API 마이그레이션 수정

---

nestjs-migration/src/auth/auth.service.ts
nestjs-migration/src/common/decorator/required-password.decorator.ts
nestjs-migration/src/common/guard/password.guard.ts
nestjs-migration/src/oauth/oauth.module.ts
nestjs-migration/src/oauth/oauth.service.ts
nestjs-migration/src/oauth/repositories/oauth-connection.repository.ts
nestjs-migration/src/user/constant/user.constants.ts
nestjs-migration/src/user/dto/update-user.dto.ts
nestjs-migration/src/user/user.controller.spec.ts
nestjs-migration/src/user/user.controller.ts
nestjs-migration/src/user/user.module.ts
nestjs-migration/src/user/user.repository.ts
nestjs-migration/src/user/user.service.spec.ts
nestjs-migration/src/user/user.service.ts

- #220
-  유저 자신의 정보 조회 API
-  비밀번호 확인 기능 가드로 구현
-  유저 정보 수정 API
-  유저 삭제 API

[BE] 유저 API 마이그레이션 마무리

---

client/package.json
client/src/component/Posts/Editer/CustomEditor.tsx
client/src/component/Posts/Editer/ImageManager.tsx
client/src/component/Posts/Editer/toolbarColors.ts
client/src/component/Posts/PostInfo.tsx
client/src/index.css
client/src/page/Posts/UpsertPostPage.tsx
client/src/style/quill-post-color.css
client/src/style/quill-post.css

- #277
- #279
<br>
게시글 편집기와 관련된 클라이언트 작업입니다.
- 글쓰기 페이지에 React Quill 에디터 적용
- 최소 기능 사용: 굵기, 밑줄, 크기, 폰트, 텍스트 컬러, 이미지
- 게시글 열람 페이지의 게시글 영역 스타일 작성: `ql-`로 시작하는 className
- 게시글 에디터에서도 게시글 열람 페이지와 동일하게 보이도록 스타일링
- 다크 모드를 위한 글자색 처리: 에디터 기본값인 인라인 스타일 하드코딩에서 className 부여 방식으로 변경
- 이미지 파일 관리
- 이미지 첨부 구현: 서버에 이미지 업로드 요청 후 URL을 받아서 본문에 `<img>` 엘리먼트 삽입
- 업로드한 이미지 목록 — Quill 에디터 객체에 접근하여, S3에 업로드한 이미지 목록 추출
> <details><summary>후속 진행 예정 작업</summary>
>
> - 업로드한 이미지 삭제: 서버로 삭제 요청 후 에디터에 반영
> - 이미지 편집: 크기 조정
>
> </details>
<br>
에디터 폭을 게시글 열람 페이지의 너비와 맞췄습니다.
"같은 자리 = 같은 className"입니다.
<br>
<br>
- 업로드한 이미지 목록을 게시글 내용에서 추출했는데, 이렇게 구현해도 괜찮을까요?
- 이렇게 하면 나중에 이미지 삭제 기능을 넣었을 때, 다른 유저가 업로드한 이미지를 S3에서 제거할 수 있게 됩니다.
- 시나리오: 타인의 글에서 첨부 이미지 복사 → 내 글에 붙여넣기 → 첨부한 이미지 목록에 뜨는 타인의 이미지 삭제
- 잘못 구현되었거나 변경했으면 하는 부분 있으면 말씀해 주세요. …

[FE] 게시글 편집기 및 게시글 열람 페이지

---

nestjs-migration/src/app.module.ts
nestjs-migration/src/comment/comment.repository.ts
nestjs-migration/src/post/post.repository.ts
nestjs-migration/src/rank/constant/rank.constants.ts
nestjs-migration/src/rank/dto/get-top-activities.dto.ts
nestjs-migration/src/rank/dto/get-top-comments.dto.ts
nestjs-migration/src/rank/dto/get-top-posts.dto.ts
nestjs-migration/src/rank/dto/rank-results.dto.ts
nestjs-migration/src/rank/rank.controller.spec.ts
nestjs-migration/src/rank/rank.controller.ts
nestjs-migration/src/rank/rank.module.ts
nestjs-migration/src/rank/rank.service.spec.ts
nestjs-migration/src/rank/rank.service.ts
nestjs-migration/src/user/user.repository.ts

* #222 중 랭킹 개발
> 메인페이지 랭킹 기능 3가지를 구현했습니다.
- 좋아요 수 동일 시 오래된 게시물 먼저
- 삭제된 게시물을 포함하지 않습니다
- 좋아요 수 동일 시 오래된 댓글 먼저
- 삭제된 댓글은 포함하지 않습니다
- 개수 동일 시 오래된 유저 먼저
- 삭제된 게시물과 댓글은 포함하지 않습니다
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

[BE] 메인페이지 랭킹 추가

---

sql/04_posts.sql

- N/A
- `posts` 테이블 생성 시 발생하는 오류를 해결합니다.
- 필요한 자리에 누락된 `,` 보충
- 이 PR은 바로 머지하겠습니다.

[DB] posts 테이블 CREATE 문 오류 해결

---

client/src/App.tsx
client/src/api/posts/crud.ts
client/src/component/Header/Header.tsx
client/src/component/Posts/Editer/ImageManager.tsx
client/src/component/Posts/PostInfo.tsx
client/src/hook/useCategory.ts
client/src/hook/useParsedSearchParams.ts
client/src/hook/usePostList.ts
client/src/page/Category/Community.tsx
client/src/page/Main/Main.tsx
client/src/page/Posts/UpsertPostPage.tsx
shared/community/posts/post_mapper.ts
shared/community/posts/posts.ts

- #288
- #224
- #224 의 선행 작업으로 클라이언트의 게시글 기능을 확장하여 카테고리를 구현합니다.
- 게시글 목록 조회 시 클라이언트와 서버에서 사용하는 서치 파라미터 훅 구조 변경
- 파싱된 개별 값, 개별 값 갱신 함수만을 노출하고, 다음 searchParams를 생성하고 갱신하는 처리는 훅 내부로 이동 (바깥 코드를 간결하게)
- 카테고리 메타데이터 정리 (ID에 따른 카테고리 이름, 카테고리 설명, 클라이언트 라우팅 경로 등)
- 카테고리 ID로 게시판 구분
- 게시글 작성 페이지 및 게시글 생성 요청에 카테고리 ID 적용
- 잘못 구현되었거나 수정 필요한 부분 있으면 말씀해 주세요!

[FE] 게시글 카테고리 기능

---

nestjs-migration/src/comment/comment.repository.ts
nestjs-migration/src/post/post.repository.ts

> #293 관련 오류 수정
* 포스트, 댓글 랭킹 leftjoin, innerjoin, Count 문법 수정
* 페이지네이션 total - category_id에 따라 올 수 있도록
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex: 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[fix] : 랭킹 API 오류 및 카테고리 페이징 수정

---

client/src/api/posts/qna_crud.ts
client/src/component/Comments/CommentItem/CommentItem.tsx
client/src/component/Comments/Comments.tsx
client/src/component/Posts/Editer/ImageManager.tsx
client/src/component/Posts/PostList/EmptyPostListBody.tsx
client/src/component/Posts/PostList/PostList.tsx
client/src/hook/usePostList.ts
client/src/page/error/NotFound.tsx
client/src/state/PostInfoStore.ts
client/src/style/quill/quill.css
client/src/style/quill/toolbar.css

- #224
- #309
- #230
- #320
- Q&A 게시판의 글 목록, 게시글 열람 페이지에서 서버에 실제 데이터를 요청하는 로직을 작성합니다.
- Resolves #316
- <mark>**중요**: `.env` 파일에 아래 내용이 정의되어야 올바르게 작동합니다.</mark>
```sh
VITE_BUCKET_NAME=${BUCKET_NAME}
VITE_REGION=${REGION}
```
- 임의의 댓글 A의 좋아요를 토글한 상태에서 새 댓글을 작성할 때, 댓글 A의 좋아요 표시가 반전되는 문제를 해결합니다.
<details><summary>Details</summary>
> <img width="824" alt="qna" src="https://github.com/user-attachments/assets/92680719-9c1e-4550-a29e-095fd2da0d8f">
>
> ---
</details>
- 잘못 구현되었거나 변경 필요한 부분이 있다면 말씀해 주세요.

[FE] Q&A 게시판 API 호출 구현

---

client/src/component/common/TextInput.tsx

- `<TextInput>` 컴포넌트가 invalid 상태일 때의 배경색에 불투명도를 부여하여 다크모드에서도 글자와 배경이 구분되도록 수정합니다.
- 배경색을 `red-50`에서 `red-500`, 불투명도 5%로 변경합니다.

🐛 [fix] : 다크모드에서 TextInput 컴포넌트 invalid 상태 시인성 개선

---

client/index.html
client/src/App.tsx
client/src/component/Chats/ChatRoom/SideBar/ChatRoomSideBar.tsx
client/src/component/Coupon/coupon.tsx
client/src/component/Posts/Editer/ImageManager.tsx
client/src/component/Posts/PostInfo.tsx
client/src/component/Profile/Modal/PasswordUpdateModal.tsx
client/src/component/User/OAuthLoginButtons.tsx
client/src/component/common/Toast/Toast.tsx
client/src/component/common/Toast/ToastItem.tsx
client/src/page/Profile/ProfilePage.tsx
client/src/page/User/CheckPassword.tsx
client/src/page/User/EmailRegistration.tsx
client/src/page/User/Join.tsx
client/src/page/User/Login.tsx
client/src/page/User/ProfileUpdate.tsx
client/src/state/ToastStore.ts
client/src/vite-env.d.ts

- #225
Toast 컴포넌트 작성
- 전역 상태
- `client/src/state/ToastStore.ts`
- 컴포넌트 작성 및 연결: Toast, ToastItem
- `client/src/component/common/Toast/Toast.tsx`
- `client/src/component/common/Toast/ToastItem.tsx`
- Alert 형태의 모달 일부를 토스트로 교체
```tsx
const Sample: React.FC = () => {
const toast = useToast();
const handleClick = () => {
toast.add({
message: "토스트 메시지",
variant: "success", // optional (error, warning, success, 기본값 info)
});
};
return (
<button onClick={handleClick}>
클릭하여 토스트 띄우기
</button>
);
};
```

✨ [feat] : Toast 컴포넌트 작성 및 일부 모달을 토스트로 대체
